### ISSUE TITLE
Bookmark on trending

### ISSUE THREAD

**Issue by Nitish814112** [yashtibrewal/entertainment-app-frontend#45]
Need to use the bookmark component for the trending cards as well.

![image](https://github.com/user-attachments/assets/61e34a32-89b4-4594-ad15-d70471072dba)

**Comment by yashtibrewal** [comment]
New apporach is required to fix this.

1. Either remove bookmarks functionality all together just on the trending cards.
2. Or create common store variable which handles the bookmarks on the home page due to duplicate content in trending and recommended for you.
3. Or update the recommended logic to not have trending content.

Looking for suggestions.

**Comment by yashtibrewal** [comment]
I am using the first approach.

Future scope of project : 2 or 3.
